### ISSUE TITLE
font awesome

### ISSUE THREAD

**Issue by Swissgroover** [Swissgroover/Link-Team#13]
Kategooriate ikoonid :)

**Comment by Merike11** [comment]
shopping: https://fontawesome.com/icons/shopping-cart?style=solid
home:       https://fontawesome.com/icons/store-alt?style=solid
travel:        https://fontawesome.com/icons/car-bus?style=regular
                  https://fontawesome.com/icons/globe-africa?style=solid
bills:           https://fontawesome.com/icons/file-invoice?style=solid
micell:        https://fontawesome.com/icons/compress-arrows-alt?style=solid
income:     https://fontawesome.com/icons/wallet?style=solid
